from loguru import logger

import subprocess

# 修改时区
'''
[{"value":"Dateline Standard Time","name":"(UTC-12:00) 国际日期变更线西"},
{"value":"UTC-11","name":"(UTC-11:00) 协调世界时-11"},
{"value":"Aleutian Standard Time","name":"(UTC-10:00) 阿留申群岛"},
{"value":"Hawaiian Standard Time","name":"(UTC-10:00) 夏威夷"},
{"value":"Marquesas Standard Time","name":"(UTC-09:30) 马克萨斯群岛"},
{"value":"Alaskan Standard Time","name":"(UTC-09:00) 阿拉斯加"},
{"value":"UTC-09","name":"(UTC-09:00) 协调世界时-09"},
{"value":"Pacific Standard Time","name":"(UTC-08:00) 太平洋时间(美国和加拿大)"},
{"value":"Pacific Standard Time (Mexico)","name":"(UTC-08:00) 下加利福尼亚州"},
{"value":"UTC-08","name":"(UTC-08:00) 协调世界时-08"},
{"value":"Mountain Standard Time (Mexico)","name":"(UTC-07:00) 奇瓦瓦，拉巴斯，马萨特兰"},
{"value":"Mountain Standard Time","name":"(UTC-07:00) 山地时间(美国和加拿大)"},
{"value":"US Mountain Standard Time","name":"(UTC-07:00) 亚利桑那"},
{"value":"Easter Island Standard Time","name":"(UTC-06:00) 复活节岛"},
{"value":"Central Standard Time (Mexico)","name":"(UTC-06:00) 瓜达拉哈拉，墨西哥城，蒙特雷"},
{"value":"Canada Central Standard Time","name":"(UTC-06:00) 萨斯喀彻温"},
{"value":"Central Standard Time","name":"(UTC-06:00) 中部时间(美国和加拿大)"},
{"value":"Central America Standard Time","name":"(UTC-06:00) 中美洲"},
{"value":"SA Pacific Standard Time","name":"(UTC-05:00) 波哥大，利马，基多，里奥布朗库"},
{"value":"Eastern Standard Time","name":"(UTC-05:00) 东部时间(美国和加拿大)"},
{"value":"Cuba Standard Time","name":"(UTC-05:00) 哈瓦那"},
{"value":"Haiti Standard Time","name":"(UTC-05:00) 海地"},
{"value":"Eastern Standard Time (Mexico)","name":"(UTC-05:00) 切图马尔"},
{"value":"Turks And Caicos Standard Time","name":"(UTC-05:00) 特克斯和凯科斯群岛"},
{"value":"US Eastern Standard Time","name":"(UTC-05:00) 印地安那州(东部)"},
{"value":"Atlantic Standard Time","name":"(UTC-04:00) 大西洋时间(加拿大)"},
{"value":"Venezuela Standard Time","name":"(UTC-04:00) 加拉加斯"},
{"value":"Central Brazilian Standard Time","name":"(UTC-04:00) 库亚巴"},
{"value":"SA Western Standard Time","name":"(UTC-04:00) 乔治敦，拉巴斯，马瑙斯，圣胡安"},
{"value":"Pacific SA Standard Time","name":"(UTC-04:00) 圣地亚哥"},
{"value":"Paraguay Standard Time","name":"(UTC-04:00) 亚松森"},
{"value":"Newfoundland Standard Time","name":"(UTC-03:30) 纽芬兰"},
{"value":"Tocantins Standard Time","name":"(UTC-03:00) 阿拉瓜伊纳"},
{"value":"E. South America Standard Time","name":"(UTC-03:00) 巴西利亚"},
{"value":"Argentina Standard Time","name":"(UTC-03:00) 布宜诺斯艾利斯"},
{"value":"Greenland Standard Time","name":"(UTC-03:00) 格陵兰"},
{"value":"SA Eastern Standard Time","name":"(UTC-03:00) 卡宴，福塔雷萨"},
{"value":"Montevideo Standard Time","name":"(UTC-03:00) 蒙得维的亚"},
{"value":"Magallanes Standard Time","name":"(UTC-03:00) 蓬塔阿雷纳斯"},
{"value":"Bahia Standard Time","name":"(UTC-03:00) 萨尔瓦多"},
{"value":"Saint Pierre Standard Time","name":"(UTC-03:00) 圣皮埃尔和密克隆群岛"},
{"value":"UTC-02","name":"(UTC-02:00) 协调世界时-02"},
{"value":"Cape Verde Standard Time","name":"(UTC-01:00) 佛得角群岛"},
{"value":"Azores Standard Time","name":"(UTC-01:00) 亚速尔群岛"},
{"value":"UTC","name":"(UTC) 协调世界时"},
{"value":"GMT Standard Time","name":"(UTC+00:00) 都柏林，爱丁堡，里斯本，伦敦"},
{"value":"Greenwich Standard Time","name":"(UTC+00:00) 蒙罗维亚，雷克雅未克"},
{"value":"Sao Tome Standard Time","name":"(UTC+00:00) 圣多美"},
{"value":"W. Europe Standard Time","name":"(UTC+01:00) 阿姆斯特丹，柏林，伯尔尼，罗马，斯德哥尔摩，维也纳"},
{"value":"Central Europe Standard Time","name":"(UTC+01:00) 贝尔格莱德，布拉迪斯拉发，布达佩斯，卢布尔雅那，布拉格"},
{"value":"Romance Standard Time","name":"(UTC+01:00) 布鲁塞尔，哥本哈根，马德里，巴黎"},
{"value":"Morocco Standard Time","name":"(UTC+01:00) 卡萨布兰卡"},
{"value":"Central European Standard Time","name":"(UTC+01:00) 萨拉热窝，斯科普里，华沙，萨格勒布"},
{"value":"W. Central Africa Standard Time","name":"(UTC+01:00) 中非西部"},
{"value":"Jordan Standard Time","name":"(UTC+02:00) 安曼"},
{"value":"Middle East Standard Time","name":"(UTC+02:00) 贝鲁特"},
{"value":"Syria Standard Time","name":"(UTC+02:00) 大马士革"},
{"value":"Libya Standard Time","name":"(UTC+02:00) 的黎波里"},
{"value":"South Africa Standard Time","name":"(UTC+02:00) 哈拉雷，比勒陀利亚"},
{"value":"FLE Standard Time","name":"(UTC+02:00) 赫尔辛基，基辅，里加，索非亚，塔林，维尔纽斯"},
{"value":"E. Europe Standard Time","name":"(UTC+02:00) 基希讷乌"},
{"value":"Kaliningrad Standard Time","name":"(UTC+02:00) 加里宁格勒"},
{"value":"West Bank Standard Time","name":"(UTC+02:00) 加沙，希伯伦"},
{"value":"Sudan Standard Time","name":"(UTC+02:00) 喀土穆"},
{"value":"Egypt Standard Time","name":"(UTC+02:00) 开罗"},
{"value":"Namibia Standard Time","name":"(UTC+02:00) 温得和克"},
{"value":"GTB Standard Time","name":"(UTC+02:00) 雅典，布加勒斯特"},
{"value":"Israel Standard Time","name":"(UTC+02:00) 耶路撒冷"},
{"value":"Arabic Standard Time","name":"(UTC+03:00) 巴格达"},
{"value":"Arab Standard Time","name":"(UTC+03:00) 科威特，利雅得"},
{"value":"Belarus Standard Time","name":"(UTC+03:00) 明斯克"},
{"value":"Russian Standard Time","name":"(UTC+03:00) 莫斯科，圣彼得堡"},
{"value":"E. Africa Standard Time","name":"(UTC+03:00) 内罗毕"},
{"value":"Turkey Standard Time","name":"(UTC+03:00) 伊斯坦布尔"},
{"value":"Iran Standard Time","name":"(UTC+03:30) 德黑兰"},
{"value":"Arabian Standard Time","name":"(UTC+04:00) 阿布扎比，马斯喀特"},
{"value":"Astrakhan Standard Time","name":"(UTC+04:00) 阿斯特拉罕，乌里扬诺夫斯克"},
{"value":"Caucasus Standard Time","name":"(UTC+04:00) 埃里温"},
{"value":"Azerbaijan Standard Time","name":"(UTC+04:00) 巴库"},
{"value":"Georgian Standard Time","name":"(UTC+04:00) 第比利斯"},
{"value":"Volgograd Standard Time","name":"(UTC+04:00) 伏尔加格勒"},
{"value":"Mauritius Standard Time","name":"(UTC+04:00) 路易港"},
{"value":"Saratov Standard Time","name":"(UTC+04:00) 萨拉托夫"},
{"value":"Russia Time Zone 3","name":"(UTC+04:00) 伊热夫斯克，萨马拉"},
{"value":"Afghanistan Standard Time","name":"(UTC+04:30) 喀布尔"},
{"value":"West Asia Standard Time","name":"(UTC+05:00) 阿什哈巴德，塔什干"},
{"value":"Qyzylorda Standard Time","name":"(UTC+05:00) 克孜洛尔达"},
{"value":"Ekaterinburg Standard Time","name":"(UTC+05:00) 叶卡捷琳堡"},
{"value":"Pakistan Standard Time","name":"(UTC+05:00) 伊斯兰堡，卡拉奇"},
{"value":"India Standard Time","name":"(UTC+05:30) 钦奈，加尔各答，孟买，新德里"},
{"value":"Sri Lanka Standard Time","name":"(UTC+05:30) 斯里加亚渥登普拉"},
{"value":"Nepal Standard Time","name":"(UTC+05:45) 加德满都"},
{"value":"Central Asia Standard Time","name":"(UTC+06:00) 阿斯塔纳"},
{"value":"Bangladesh Standard Time","name":"(UTC+06:00) 达卡"},
{"value":"Omsk Standard Time","name":"(UTC+06:00) 鄂木斯克"},
{"value":"Myanmar Standard Time","name":"(UTC+06:30) 仰光"},
{"value":"Altai Standard Time","name":"(UTC+07:00) 巴尔瑙尔，戈尔诺-阿尔泰斯克"},
{"value":"W. Mongolia Standard Time","name":"(UTC+07:00) 科布多"},
{"value":"North Asia Standard Time","name":"(UTC+07:00) 克拉斯诺亚尔斯克"},
{"value":"SE Asia Standard Time","name":"(UTC+07:00) 曼谷，河内，雅加达"},
{"value":"Tomsk Standard Time","name":"(UTC+07:00) 托木斯克"},
{"value":"N. Central Asia Standard Time","name":"(UTC+07:00) 新西伯利亚"},
{"value":"China Standard Time","name":"(UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐"},
{"value":"Singapore Standard Time","name":"(UTC+08:00) 吉隆坡，新加坡"},
{"value":"W. Australia Standard Time","name":"(UTC+08:00) 珀斯"},
{"value":"Taipei Standard Time","name":"(UTC+08:00) 台北"},
{"value":"Ulaanbaatar Standard Time","name":"(UTC+08:00) 乌兰巴托"},
{"value":"North Asia East Standard Time","name":"(UTC+08:00) 伊尔库茨克"},
{"value":"Aus Central W. Standard Time","name":"(UTC+08:45) 尤克拉"},
{"value":"Transbaikal Standard Time","name":"(UTC+09:00) 赤塔市"},
{"value":"Tokyo Standard Time","name":"(UTC+09:00) 大阪，札幌，东京"},
{"value":"North Korea Standard Time","name":"(UTC+09:00) 平壤"},
{"value":"Korea Standard Time","name":"(UTC+09:00) 首尔"},
{"value":"Yakutsk Standard Time","name":"(UTC+09:00) 雅库茨克"},
{"value":"Cen. Australia Standard Time","name":"(UTC+09:30) 阿德莱德"},
{"value":"AUS Central Standard Time","name":"(UTC+09:30) 达尔文"},
{"value":"E. Australia Standard Time","name":"(UTC+10:00) 布里斯班"},
{"value":"Vladivostok Standard Time","name":"(UTC+10:00) 符拉迪沃斯托克"},
{"value":"West Pacific Standard Time","name":"(UTC+10:00) 关岛，莫尔兹比港"},
{"value":"Tasmania Standard Time","name":"(UTC+10:00) 霍巴特"},
{"value":"AUS Eastern Standard Time","name":"(UTC+10:00) 堪培拉，墨尔本，悉尼"},
{"value":"Lord Howe Standard Time","name":"(UTC+10:30) 豪勋爵岛"},
{"value":"Bougainville Standard Time","name":"(UTC+11:00) 布干维尔岛"},
{"value":"Magadan Standard Time","name":"(UTC+11:00) 马加丹"},
{"value":"Norfolk Standard Time","name":"(UTC+11:00) 诺福克岛"},
{"value":"Russia Time Zone 10","name":"(UTC+11:00) 乔库尔达赫"},
{"value":"Sakhalin Standard Time","name":"(UTC+11:00) 萨哈林"},
{"value":"Central Pacific Standard Time","name":"(UTC+11:00) 所罗门群岛，新喀里多尼亚"},
{"value":"Russia Time Zone 11","name":"(UTC+12:00) 阿纳德尔，堪察加彼得罗巴甫洛夫斯克"},
{"value":"New Zealand Standard Time","name":"(UTC+12:00) 奥克兰，惠灵顿"},
{"value":"Fiji Standard Time","name":"(UTC+12:00) 斐济"},
{"value":"UTC+12","name":"(UTC+12:00) 协调世界时+12"},
{"value":"Chatham Islands Standard Time","name":"(UTC+12:45) 查塔姆群岛"},
{"value":"Tonga Standard Time","name":"(UTC+13:00) 努库阿洛法"},
{"value":"Samoa Standard Time","name":"(UTC+13:00) 萨摩亚群岛"},
{"value":"UTC+13","name":"(UTC+13:00) 协调世界时+13"},
{"value":"Line Islands Standard Time","name":"(UTC+14:00) 圣诞岛"}]
'''
def set_system_timezone(new_timezone):
    try:
        subprocess.run(['tzutil', '/s', new_timezone], check=True)
        print("System timezone updated successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error updating system timezone: {e}")

# 修改语言
# [{value: 'en-US', name: '英语'},
# {value: 'zh-CN', name: '中文'}]
def set_system_language(new_language):
    try:
        subprocess.run(['powershell', '-Command', f'Set-Culture -CultureInfo {new_language}'], check=True)
        print("System language updated successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error updating system language: {e}")

# 示例：修改时区为 'Pacific Standard Time'，修改语言为英语（en-US）
if __name__ == '__main__':
    set_system_timezone('China Standard Time')
    set_system_language('zh-CN')